#!/usr/bin/env bash

## Sync your local environment with fresh data and code from Pantheon development environment.
##
## Usage: fin init

# Abort if anything fails
set -e

# SETTINGS
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

# INCLUDES
source "${PROJECT_ROOT}/.docksal/commands/common/sync_db.sh"
source "${PROJECT_ROOT}/.docksal/commands/common/sync_config.sh"


# HELPERS

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'
bg='\[\033[0;35m\]'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Windows check
is_windows ()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

# Sync db
function _sync_db {
time sync_db $REPLY;
all_done=1
}

# Sync config
function _sync_config {
time sync_config $REPLY;
all_done=1
}

# Execute
if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set!"
	exit 1
fi

# Make sure docksal is running
if [[ $DOCKER_RUNNING == "true" ]]; then
	echo -e "${green_bg} Step 1 ${NC}${green} Recreating services...${NC}"
	fin reset -f
else
	echo -e "${green_bg} Step 1 ${NC}${green} Creating services...${NC}"
	fin up
fi


# Check for a clean repository
if ! [ -z "$(git status --untracked-files=no --porcelain)" ]; then
  # Uncommitted changes in tracked files
  echo -e  "${red}WARNING: You have uncommitted changes in your branch.${NC}"
  echo
  echo -e "Commit or stash your changes prior to continuing, and then re-run fin sync:"
  echo
  git status
  exit 1
fi

# Pull the latest code from
echo -e  "${green_bg} Step 2 ${NC}${green} Pulling $GIT_BRANCH branch from Github...${NC}"
git pull origin $GIT_BRANCH

# Run composer install
echo -e "${green_bg} Step 3 ${NC}${green} Running composer install...${NC}"
composer install

# Start database sync
echo -e "${green_bg} Step 4 ${NC}${green} Sync database with upstream${NC}"
time sync_db $1


exit

sleep 2
#-------------------------- END: Execution --------------------------------



