#!/usr/bin/env bash

## Sync your local environment with fresh data and code from Pantheon development environment.
##
## Usage: fin sync

# Abort if anything fails
set -e

# SETTINGS
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

# INCLUDES
source "${PROJECT_ROOT}/.docksal/commands/common/sync_db.sh"
source "${PROJECT_ROOT}/.docksal/commands/common/sync_config.sh"


# HELPERS

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'
bg='\[\033[0;35m\]'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Windows check
is_windows ()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

# Sync db
function _sync_db {
time sync_db $REPLY;
all_done=1
}

# Sync config
function _sync_config {
time sync_config $REPLY;
all_done=1
}


# Execute
if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set!"
	exit 1
fi

# Check for a clean repository
if ! [ -z "$(git status --untracked-files=no --porcelain)" ]; then
  # Uncommitted changes in tracked files
  echo -e  "${red}WARNING: You have uncommitted changes in your branch.${NC}"
  echo
  echo -e "Commit or stash your changes prior to continuing, and then re-run fin sync:"
  echo
  git status
  exit 1
fi

# Make sure docksal is running
fin up

# Start database sync
echo -e "${green_bg} Step 1 ${NC}${green} Import database from:${NC}"

all_done=0
while (( !all_done )); do
    options=($PANTHEON_SITE_ENV 'none' 'exit')
    select opt in "${options[@]}"; do
        case $REPLY in
            1) _sync_db; exit ;;
            2) _sync_config; exit ;;
            3) exit ;;
            *) echo "Invalid option" ;;
     esac
    done
done

exit

sleep 2